### ISSUE TITLE
Establishing initial data analysis strategy

### ISSUE THREAD

**Issue by swiri021** [OpenKBC/multiple_sclerosis_proj#3]
dataset summary (what we have, what we can do), data analysis strategy

**Comment by swiri021** [comment]
### Early diagnosis biomarker: 
1. Getting DEG (Early vs Late vs Normal)
2. Getting Differential pathways (Early vs Late vs Normal)
3. Feature Extraction(RFE) (Early vs Normal)
4. PCA (Early vs Late vs Normal) with clustering methods
5. Intersected features among all methods and curation with scientific insight(Kicheol)
6. Performance test (AUC curve) with validation dataset
7. Performance test (AUC curve) with external dataset

**Comment by swiri021** [comment]
@kicheolkim We need a normalization dataset, I am able to do it by myself but I think we have to make consistency for the normalization method. A possible option could be TMM or quantile norm, let me know your thoughts.

**Comment by kicheolkim** [comment]
- We don't have actual late-stage patients. The majority of patients are early stage.
- For DEG, it should compare within cell types. I used sex and age as covariates (model: ~Last_Known_Treat_Stat + Sex + AgeAtExamGrp). The age was binned 10~30, 30~40, 40~50, 50~60, and 60~90.
[Github R code for previous DEG (used in the publication)](https://github.com/kicheolkim/RNAseq_FullTx/tree/master/R)

**Comment by swiri021** [comment]
@kicheolkim 

### Initial feature extraction
* **Experiment group:** early stage (DiseaseDuration <= median)
* **Control group:** Late stage (DiseaseDuration > median)
Step1- Ranksum and get pvalues<0.05 from Activation Score
Step2- Recursive Feature Elimination(w/ Cross Validation) and get ranking=1 from Step1 result
Step3- Ranksum and get pvalues<0.05 from Step2 result
Step4- Recursive Feature Elimination(w/ Cross Validation) and get ranking=1 from Step3 result

* **Final number of genes = 62**

**Comment by swiri021** [comment]
New comments for actual analysis work #24
